### ISSUE TITLE
ARM Docker image

### ISSUE THREAD

**Issue by reitermarkus** [InseeFrLab/s3-operator#32]
Currently, no ARM image is available, resulting in `ImagePullBackOff` due to

```
failed to pull and unpack image "docker.io/inseefrlab/s3-operator:latest": no match for platform in manifest
```

Additionally, the Helm chart currently does not allow specifying a `nodeSelector` to prevent it from being scheduled on ARM nodes.

**Comment by alexisdondon** [comment]
Hi, thanks for the issue.

At this moment, we have not try to do this. it's not a priority for us. Anyway if you want to contribute to add arm image, we probably need to dive here https://sdk.operatorframework.io/docs/advanced-topics/multi-arch/ to make some change on pipeline github to build for multiple archs.

Allowing nodeSelector can easily be add if needed https://github.com/InseeFrLab/helm-charts/tree/master/charts/s3-operator here.

**Comment by FrankFoerster24** [comment]
@garronej: I would be also be interested in having images that can run on Macbooks.  My use case: for evaluation I run new software components on a local K3S cluster on my Macbook (ARM64) before moving on to any real environments running on AMD64.

**Comment by garronej** [comment]
@FrankFoerster24 understood.  
But are you working with [Onyxia](https://onyxia.sh) or not at all? 
@alexisdondon you can merge #32 I think. CI is red because it's on a branch but it should be OK I guess.

**Comment by FrankFoerster24** [comment]
> But are you working with [Onyxia](https://onyxia.sh/) or not at all?
I am not.  I just came across your S3 operator randomly.

**Comment by phlg** [comment]
Many thanks to everyone here, both for submitting the issue and a solution (I just merged Joseph's PR). The image building action appears to have run without issue, could you confirme [the built image](https://hub.docker.com/layers/inseefrlab/s3-operator/latest/images/sha256-807301670bde424da9f90206c366a57da8f8bc654acf55ba5b9b084f4c9ba88c?context=explore) is also working in your arm64 environment. 

Also sorry for the lack of reactivity on our end ; as Alexis mentioned aboved, the maintenance of s3-operator is really low priority for us, which caused us to overlook the contributions here.

**Comment by phlg** [comment]
Closing this as completed, hopefully the now-available ARM image is fully functional.
Feel free to comment, re-open or create new issue if not (but as we are in no capacity of actually debugging ARM images here, not sure we can do much if the need arises).
