### ISSUE TITLE
User/Group resource management

### ISSUE THREAD

**Issue by alb-car** [InseeFrLab/s3-operator#36]
Are there any plans to add management of S3 User and/or Group resources? If not, is it due to a design choice, or due to low priority? Would you accept contributions?

**Comment by alexisdondon** [comment]
Hi, thanks for making this issue.

At this time, user and group are not a priority for us as the operator is mainly used to work with https://github.com/InseeFrLab/onyxia.

In this ecosystem we rely on sts account /oidc and not internal user/group of minio.

Anyway we would enjoy it if you want to contribute.

**Comment by alb-car** [comment]
Thank you for your answer. My team and I would work on such a feature while following your code style, and then open a pull request. I opened a separate issue (#38) as something we would like to implement alongside this one, provided you accept the change.

**Comment by phlg** [comment]
From version 0.9.0 onwards (but 0.10.1+ recommended to avoid some bugs), the operator manages a S3User resource that map to Users/Access keys on Minio (thanks to the contributor @Donatien26 and fixes/tweaks by @JackLemaitre). Not sure group management is going to happen at the moment though.

For the time being, I'll close this issue, but feel free to reopen if needed.
